paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la BD
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno en el servidor
    post:
      summary: Registra un nuevo producto en la base de datos
      tags:
        - Products
      response:
        "200":
          description: El nuevo producto se registró con éxito
        "500":
          description: Error interno en el servidor
components:
  schemas:
    Producto:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerada por MongoDB
        title:
          type: String
          description: Título del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Stock del producto
        category:
          type: String
          description: Categoría del producto
        thumbnail:
          type: String
          description: Imágenes del producto
        owner:
          type: String
          description: Creador del producto
      example:
        _id: ObjectId("6507a13256f257fb0fdda04a")
        title: Jean regular
        description: Jean negro, recto con puño
        price: 75
        code: jean01
        stock: 15
        category: pantalones
        thumbnail: https://http2.mlstatic.com/D_NQ_NP_884262-MLU72365605295_102023-O.webp
        owner: leandro@gmail.com
